from .weather_service import WeatherService
from .coordinates_service import CoordinatesService
from repositories import weather_api_repository, coordinates_api_repository

weather_service = WeatherService(weather_api_repository, coordinates_api_repository)
coordinates_service = CoordinatesService(coordinates_api_repository)