from .weather_service import WeatherService
from .location_service import LocationService
from repositories import weather_api_repository, location_api_repository

weather_service = WeatherService(weather_api_repository, location_api_repository)
location_service = LocationService(location_api_repository)